### PR TITLE
Update project and add the `id` parameter 

### PR DESCRIPTION
**Pull request by layoutd**
**This PR:**

- Includes the `utm_id` parameter
- Adds an `.nvmrc` file for Node.js v20 (lts/iron) and the `package-lock.json` file
- Updates the NPM versions and dependencies to build correctly with v20
- Swaps in `sass=dart-sass` instead of `node-sass`
- Adds new `dist` files for v1.1.2 with the above changes

**Testing**
1. Confirm that `nvm run build` works without errors after `nvm use` or `nvm install`
  - There is one gem that I had to install, too, for generating the demo files: `sudo gem install slim` 
3. Make the built `/public/`directory available to a browser.
4. Copy one of the UTM test links at the bottom into an (incognito?) browser window.
5. Confirm the [ID value](https://en.wikipedia.org/wiki/WooCommerce#:~:text=WordPress.%20Launched%20on-,September%2027%2C%202011,-%2C%5B3%5D) is displayed correctly in First visit and Current visit:
    image
6. Update the `utm_id` value and confirm that the Current visit ID value changes.

### CODE REVIEW

**Review by budzanowski — APPROVED** [review]

**Review by budzanowski — DISMISSED** [review]
Can't build.

**Comment by budzanowski** [comment]
Sorry for the premature review! I thought that I am on a different PR.

**Review by budzanowski — APPROVED** [review]
It builds correctly!

Please add full build instructions to the Readme.md

**Comment by layoutd** [comment]
Thanks @budzanowski. Build instructions added in https://github.com/woocommerce/sourcebuster-js/pull/1/commits/bcc4951e8e0394d8c780ffeecd96bdc069a65e60

**Pull request merged**
